### ISSUE TITLE
GUI installation error with ZSH

### ISSUE THREAD

**Issue by arepstein** [mishioo/tesliper#5]
Hi, I had a small issue installing the gui with a zsh shell. I needed to escape the brackets, i.e. `pip install tesliper\[gui\]` instead of `pip install tesliper[gui]`.

**Comment by mishioo** [comment]
I'm not familiar with zsh, but [this stackexchange answer](https://apple.stackexchange.com/a/427617) explains that this is due to how zsh resolves `some[thing]` syntax, so the issue is not related to `tesliper`. Anyway, I will add a note about this for zsh users in the "Installation" section of docs.

**Comment by arepstein** [comment]
Thanks! Yes I see that's not related tesliper, but with zsh as the default for Mac users I think a note makes sense.
